global:
  resolve_timeout: 24h  # Time to wait for alert resolution

route:
  group_by: [cluster, alertname]
  group_wait: 0s
  group_interval: 5m
  repeat_interval: 4h
  #group_by: ['cluster', 'alertname']
  receiver: all_receivers

receivers:
  - name: all_receivers
    msteams_configs:
      - webhook_url: '${MST_TEAMS_WEBHOOK_URL}'
        send_resolved: false
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        chat_id: ${TELEGRAM_CHAT_ID}
        bot_token: '${TELEGRAM_BOT_TOKEN}'
        send_resolved: false
        message: '{{ template "telegram.message" . }}'
        parse_mode: 'Markdown'

  - name: teams
    msteams_configs:
      - webhook_url: '${MST_TEAMS_WEBHOOK_URL}'
        send_resolved: false

  - name: telegram
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        chat_id: ${TELEGRAM_CHAT_ID}
        bot_token: '${TELEGRAM_BOT_TOKEN}'
        send_resolved: false
        message: '{{ template "telegram.summary" . }}'
        #message: '{{ template "telegram.message" . }}'
        parse_mode: 'Markdown'

templates:
  - '/etc/alertmanager/templates/alert.tmpl' # path to our telegram.tmpl